Mayhem
mayhemheroes/tectonic pull request #1
Opened 2022-05-16 22:25 UTC by zwimer

2022-06-08 14:24 UTC, xansec requested changes

2022-06-08 14:24 UTC, xansec commented on base.docker
> +FROM fuzzers/cargo-fuzz:0.10.0
Having two Dockerfiles is a little messy - can you use a multistage build instead, reducing image size with a package stage?

2022-06-08 14:24 UTC, xansec commented on base.docker
> +RUN echo "cargo fuzz build" >> ./run-fuzzer.sh
I looked at `run-fuzzer.sh ` and I don't think you need to use this script - you should be able to just install and run `cargo fuzz build <target>` directly.

2022-06-08 14:24 UTC, xansec commented on Mayhemfile
> +image: ghcr.io/zwimer/tectonic:mayhem
You can omit the image name.

2022-06-08 14:24 UTC, xansec commented on Mayhemfile
> +target: fuzzme
Please ensure your target name and binary/cmd name match.

2022-06-14 23:52 UTC, zwimer commented on base.docker
> +FROM fuzzers/cargo-fuzz:0.10.0
Sure

2022-06-14 23:55 UTC, zwimer commented on Mayhemfile
> +image: ghcr.io/zwimer/tectonic:mayhem
Ok

2022-06-14 23:56 UTC, zwimer commented on Mayhemfile
> +project: mayhem-targets
Changed to `tectonic`

2022-06-14 23:56 UTC, zwimer commented on Mayhemfile
> +target: fuzzme
Ok

2022-06-14 23:57 UTC, zwimer commented on base.docker
> +FROM fuzzers/cargo-fuzz:0.10.0
Done

2022-06-14 23:57 UTC, zwimer commented on base.docker
> +RUN git clone https://github.com/tectonic-typesetting/tectonic
Ok

2022-06-15 00:01 UTC, zwimer commented on base.docker
> +RUN echo "cargo fuzz build" >> ./run-fuzzer.sh
We can copy the contents to the dockerfile instead of reusing the file.

2022-06-22 21:19 UTC, r00tus3r commented
@xansec ping, do these changes look good?

2022-06-23 00:03 UTC, r00tus3r commented
@xansec Done!

2022-06-23 06:06 UTC, xansec commented
I added a few more updates, but this is good. Merging.

2022-06-23 06:06 UTC, merged